### ISSUE TITLE
Website – tracking issue

### ISSUE THREAD

**Issue by xplosionmind** [xplosionmind/ournet#7]
- [x] #17
- [x] MVP
- [x] #8
- [x] OGP image

## Pages

- [x] Homepage
- [x] Knit page
- [x] About page
  - [x] #18
- [x] (Hi)story page?
- [ ] Press kit
- [x] Visual identity page (#2)
- [ ] Resources/further reading
	- [ ] Fediverse stuff
	- [ ] IndieWeb stuff
- [ ] Inspiration (#9)

## i18n

- [x] #22
- [ ] Pages translation
	- [x] Italian translation
	- [x] French translation
	- [ ] German translation
	- [ ] Spanish translation
	- [ ] Dutch translation
- [x] Multilingual toggle for pages

## [Eleventy](https://11ty.dev 'Eleventy, a simpler static site generator')-related tasks

- [x] Use [eleventy-img plugin](https://github.com/11ty/eleventy-img 'eleventy-img GitHub repository')
